### ISSUE TITLE
TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by CRY-D** [tysonwu/stack-orderflow#7]
What does this mean?

```
python examples/01_simple_ohlcv.py        
Traceback (most recent call last):
  File "/home/android/Documents/python/Trading/stack-orderflow-master/examples/01_simple_ohlcv.py", line 4, in <module>
    from finplotter.finplotter import FinPlotter
  File "/home/android/.local/lib/python3.10/site-packages/finplotter/finplotter.py", line 6, in <module>
    import finplotter.finplot_library as fplt
  File "/home/android/.local/lib/python3.10/site-packages/finplotter/finplot_library/__init__.py", line 615, in <module>
    class FinPolyLine(pg.PolyLineROI):
  File "/home/android/.local/lib/python3.10/site-packages/finplotter/finplot_library/__init__.py", line 655, in FinPolyLine
    def movePoint(self, handle, pos, modifiers=QtCore.Qt.KeyboardModifier(), finish=True, coords='parent'):
TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'
```

**Comment by tysonwu** [comment]
This is probably because of breaking changes from PyQt5 to 6.
I have added `requirements.txt`. Let me know if it helps.

**Comment by CRY-D** [comment]
After installing all the requirements, The two examples (01, 02) works just fine, but the third fail, here is the message, I tried to play around, but I can't come up with right solution.
![Screenshot from 2023-02-23 02-32-26](https://user-images.githubusercontent.com/16564491/220802928-4fc275fd-982e-436a-b6a0-e46a23496d35.png)

**Comment by tysonwu** [comment]
Are you using strict typing tools like mypy? 

The problem originates of setting row height in the layout (`setRowStretchFactor`). [Qt6 document](https://doc.qt.io/qt-6.2/qgraphicsgridlayout.html#setRowStretchFactor) states strech_factor to be an int but it is not the case (float should work too). Seems that your setting in perhaps your Python interpreter has type checking mechanism throwing error when the this stretch_factor is not an int.

If you want to quickly make things work without disabling type checking, you can change the row_stretch_factors in `./orderflow_plotter.py`:
```
ax, ax5, ax3, ax2, ax4 = fplt.create_plot(
    ...
   # originally is [3, 0.3, 1, 1, 1]
    row_stretch_factors=[3, 1, 1, 1, 1],
)
```

**Comment by CRY-D** [comment]
Oh god, thank you, finally it works 

![Screenshot from 2023-02-23 13-37-58](https://user-images.githubusercontent.com/16564491/220908123-41191503-cc56-46ca-a31b-0acd75c03864.png)
